name: CI-CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t app .


name: EKS CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push image
      run: |
        docker build -t flask-app .
        docker tag flask-app:latest <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        docker push <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name devops-eks

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/flask-app -n production
